type: "transformation"
version: "1.0"
pipeline:
  components:
    PATIENT_STAGE:
      type: "table-input"
      parameters:
        componentName: "PATIENT_STAGE"
        database: "DATALAKE"
        schema: "RAW_SCHEMA"
        targetTable: "PATIENT_STAGE"
        columnNames:
        - "PATIENT_ID"
        - "FIRST_NAME"
        - "LAST_NAME"
        - "ADDRESS"
        - "CONTACT_NUMBER"
        timeOffset:
    PATIENT_DIM:
      type: "table-input"
      parameters:
        componentName: "PATIENT_DIM"
        database: "[Environment Default]"
        schema: "RAW_SCHEMA"
        targetTable: "PATIENT_SCD2"
        columnNames:
        - "PATIENT_ID"
        - "FIRST_NAME"
        - "LAST_NAME"
        - "ADDRESS"
        - "CONTACT_NUMBER"
        timeOffset:
    Detect Changes:
      type: "detect-changes"
      sources:
      - "PATIENT_DIM"
      - "PATIENT_STAGE"
      parameters:
        componentName: "Detect Changes"
        masterTable: "PATIENT_DIM"
        matchKeys:
        - "PATIENT_ID"
        compareColumns:
        - "PATIENT_ID"
        - "FIRST_NAME"
        - "LAST_NAME"
        - "ADDRESS"
        - "CONTACT_NUMBER"
        outputColumnMapping:
        - - "master_PATIENT_ID"
          - "master_PATIENT_ID"
        - - "compare_PATIENT_ID"
          - "compare_PATIENT_ID"
        - - "master_FIRST_NAME"
          - "master_FIRST_NAME"
        - - "compare_FIRST_NAME"
          - "compare_FIRST_NAME"
        - - "master_LAST_NAME"
          - "master_LAST_NAME"
        - - "compare_LAST_NAME"
          - "compare_LAST_NAME"
        - - "master_ADDRESS"
          - "master_ADDRESS"
        - - "compare_ADDRESS"
          - "compare_ADDRESS"
        - - "master_CONTACT_NUMBER"
          - "master_CONTACT_NUMBER"
        - - "compare_CONTACT_NUMBER"
          - "compare_CONTACT_NUMBER"
        indicatorColumn: "Indicator"
    FilterC Records:
      type: "filter"
      sources:
      - "Detect Changes"
      parameters:
        componentName: "FilterC Records"
        filterConditions:
        - - "Indicator"
          - "Is"
          - "Equal to"
          - "C"
        combineCondition: "Or"
    Calculator:
      type: "calculator"
      sources:
      - "FilterC Records"
      parameters:
        componentName: "Calculator"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_DATE()"
          - "START_DATE"
        - - "1"
          - "IS_ACTIVE"
        - - "'2099-12-31'"
          - "END_DATE"
    PATIENT_SCD2:
      type: "table-output"
      sources:
      - "Calculator"
      parameters:
        componentName: "PATIENT_SCD2"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "RAW_SCHEMA"
        targetTable: "PATIENT_SCD2"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "PATIENT_ID"
          - "PATIENT_ID"
        - - "compare_FIRST_NAME"
          - "FIRST_NAME"
        - - "compare_LAST_NAME"
          - "LAST_NAME"
        - - "compare_ADDRESS"
          - "ADDRESS"
        - - "compare_CONTACT_NUMBER"
          - "CONTACT_NUMBER"
        - - "START_DATE"
          - "START_DATE"
        - - "END_DATE"
          - "END_DATE"
        - - "IS_ACTIVE"
          - "IS_ACTIVE"
        orderBy:
        outputMode: "Append"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    PATIENT_STAGE:
      position:
        x: -130
        "y": 240
      tempMetlId: 1
    PATIENT_DIM:
      position:
        x: -130
        "y": 100
      tempMetlId: 2
    Detect Changes:
      position:
        x: 80
        "y": 170
      tempMetlId: 3
    FilterC Records:
      position:
        x: 240
        "y": 170
      tempMetlId: 4
    Calculator:
      position:
        x: 410
        "y": 170
      tempMetlId: 6
    PATIENT_SCD2:
      position:
        x: 570
        "y": 170
      tempMetlId: 7
