type: "transformation"
version: "1.0"
pipeline:
  components:
    PATIENT_STAGE:
      type: "table-input"
      parameters:
        componentName: "PATIENT_STAGE"
        database: "DATALAKE"
        schema: "RAW_SCHEMA"
        targetTable: "PATIENT_STAGE"
        columnNames:
        - "PATIENT_ID"
        - "FIRST_NAME"
        - "LAST_NAME"
        - "ADDRESS"
        - "CONTACT_NUMBER"
        timeOffset:
    PATIENT_SCD2:
      type: "table-input"
      parameters:
        componentName: "PATIENT_SCD2"
        database: "[Environment Default]"
        schema: "RAW_SCHEMA"
        targetTable: "PATIENT_SCD2"
        columnNames:
        - "PATIENT_ID"
        - "FIRST_NAME"
        - "LAST_NAME"
        - "ADDRESS"
        - "CONTACT_NUMBER"
        timeOffset:
    Detect Changes:
      type: "detect-changes"
      sources:
      - "PATIENT_SCD2"
      - "PATIENT_STAGE"
      parameters:
        componentName: "Detect Changes"
        masterTable: "PATIENT_SCD2"
        matchKeys:
        - "PATIENT_ID"
        compareColumns:
        - "PATIENT_ID"
        - "FIRST_NAME"
        - "LAST_NAME"
        - "ADDRESS"
        - "CONTACT_NUMBER"
        outputColumnMapping:
        - - "master_PATIENT_ID"
          - "master_PATIENT_ID"
        - - "compare_PATIENT_ID"
          - "compare_PATIENT_ID"
        - - "master_FIRST_NAME"
          - "master_FIRST_NAME"
        - - "compare_FIRST_NAME"
          - "compare_FIRST_NAME"
        - - "master_LAST_NAME"
          - "master_LAST_NAME"
        - - "compare_LAST_NAME"
          - "compare_LAST_NAME"
        - - "master_ADDRESS"
          - "master_ADDRESS"
        - - "compare_ADDRESS"
          - "compare_ADDRESS"
        - - "master_CONTACT_NUMBER"
          - "master_CONTACT_NUMBER"
        - - "compare_CONTACT_NUMBER"
          - "compare_CONTACT_NUMBER"
        indicatorColumn: "Indicator"
    Filter N&C Records:
      type: "filter"
      sources:
      - "Detect Changes"
      parameters:
        componentName: "Filter N&C Records"
        filterConditions:
        - - "Indicator"
          - "Is"
          - "Equal to"
          - "N"
        - - "Indicator"
          - "Is"
          - "Equal to"
          - "C"
        combineCondition: "Or"
    PATIENT_DIM 2:
      type: "table-update"
      sources:
      - "Calculator"
      parameters:
        componentName: "PATIENT_DIM 2"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "RAW_SCHEMA"
        targetTable: "PATIENT_SCD2"
        targetAlias: "target"
        sourceAlias: "input"
        joinExpression:
        - - "\"input\".\"PATIENT_ID\"=\"target\".\"PATIENT_ID\""
          - "Case"
        whenMatched:
        - - "\"input\".\"PATIENT_ID\"=\"target\".\"PATIENT_ID\" AND \"target\".\"\
            IS_ACTIVE\"=1"
          - "Update"
        updateMapping:
        - - "CHANGE_END_DATE"
          - "END_DATE"
        - - "CHANGE_IS_ACTIVE"
          - "IS_ACTIVE"
        includeNotMatched: "Yes"
        insertMapping:
        - - "PATIENT_ID"
          - "PATIENT_ID"
        - - "compare_FIRST_NAME"
          - "FIRST_NAME"
        - - "compare_LAST_NAME"
          - "LAST_NAME"
        - - "compare_ADDRESS"
          - "ADDRESS"
        - - "compare_CONTACT_NUMBER"
          - "CONTACT_NUMBER"
        - - "START_DATE"
          - "START_DATE"
        - - "END_DATE"
          - "END_DATE"
        - - "IS_ACTIVE"
          - "IS_ACTIVE"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Calculator:
      type: "calculator"
      sources:
      - "Filter N&C Records"
      parameters:
        componentName: "Calculator"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_DATE()-1"
          - "CHANGE_END_DATE"
        - - "0"
          - "CHANGE_IS_ACTIVE"
        - - "CURRENT_DATE()"
          - "START_DATE"
        - - "1"
          - "IS_ACTIVE"
        - - "'2099-12-31'"
          - "END_DATE"
design:
  components:
    PATIENT_STAGE:
      position:
        x: -130
        "y": 240
      tempMetlId: 1
    PATIENT_SCD2:
      position:
        x: -130
        "y": 100
      tempMetlId: 2
    Detect Changes:
      position:
        x: 80
        "y": 170
      tempMetlId: 3
    Filter N&C Records:
      position:
        x: 240
        "y": 170
      tempMetlId: 4
    PATIENT_DIM 2:
      position:
        x: 550
        "y": 170
      tempMetlId: 5
    Calculator:
      position:
        x: 410
        "y": 170
      tempMetlId: 6
